version: "3"

services:
  app:
    container_name: nestapp
    restart: always
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
    - 3400:3000
    - 9229:9229
    command: npm run start:debug
    networks:
      - nestnetwork
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13-alpine
    container_name: nestdb
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    networks:
      - nestnetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    networks:
      - nestnetwork

networks:
  nestnetwork:
    driver: bridge